language: python
sudo: required
dist: xenial
python:
  - '3.6'
  - '3.7'
install:
  - pip install -q -e .
  - pip install -q pytest-cov codecov
script: pytest tests/* --cov
after_success:
  - codecov
